### ISSUE TITLE
Update minting logic to ensure we have a consistent mint address

### ISSUE THREAD

**Issue by jaysee260** [ergonames/ergo-names-backend#25]
Last month we ran a successful end to end test. However, during that test, we learned that we were not getting consistent minting addresses. After some digging, we learned this was because of a misinterpretation of [EIP-24](https://github.com/ergoplatform/eips/blob/master/eip-0024.md#artist-identity).

While we believed that the minting address was determined by the address of _the first input to the tx that issues the asset_ (regardless of whether it is a P2PK or a P2S input), we realized [EIP-24](https://github.com/ergoplatform/eips/blob/master/eip-0024.md#artist-identity) instead looks for the first P2PK input _in the chain of txs_ that lead to the asset's issuance.

This morning we had a lengthy discussion and decided on trying the following to try and solve this problem:

### Current state of things
Every time we mint, one of the first things we do is get the minting request box the user sent to our minting contract. Currently, we set that as the first input to the minting tx.

### Proposed state of things
Before getting the minting request box, grab a box with the minimum amount of ERG (0.001) from our wallet - this would be a P2PK box. Set that P2PK box from our wallet as the first input to the minting tx, and the minting request box as the second. Per EIP-24, this _should_ make it so that the minting request is consistently the ErgoNames wallet address.

### A few caveats
Because we are interested in enabling support for secondary marketplace royalties, we should ensure this first P2PK box that we set as an input to the minting tx has a value in R4 specifying the royalty amount we expect to collect.

Additionally, we should update our contract to check for this, as well as to verify that this "identity box" is returned to the ErgoNames wallet once the asset is minted.

**Comment by zackbalbin** [comment]
this commit allows for successfully submitting transaction with new contract code
[(98e21ea)](https://github.com/ergonames/ergo-names-backend/commit/98e21ea88b918a243aea11a93fd0397e57f48c0b)

**Comment by jaysee260** [comment]
> this commit allows for successfully submitting transaction with new contract code [(98e21ea)](https://github.com/ergonames/ergo-names-backend/commit/98e21ea88b918a243aea11a93fd0397e57f48c0b)

On Sunday October, 16, we ran a few minting tests and validated that we are now getting a consistent mint address!

@zackbalbin , any chance you could share the minting txs of the few successful tests we ran?

**Comment by zackbalbin** [comment]
Minted: ~nemo
Funding tx:
https://testnet.ergoplatform.com/en/transactions/8f372e47d8cc55cbb5b71c25d09455d8c97ccdb8d2f3b3ae83d4706493265435
Minting tx:
https://testnet.ergoplatform.com/en/transactions/9298e4708972aadd6d588598b16101ebd9837e44803e3a882c85f7d184ffb968

Minted: ~seperatepaymenttest
Funding tx:
https://testnet.ergoplatform.com/en/transactions/2ccfdebba4fd2881b85e2eb48aa451a5f038c10c3e32795f54db3fc2339a7db8
Minting tx:
https://testnet.ergoplatform.com/en/transactions/76c89158af57e0f0e9eb104652221e472dd950c551e5b79e4b8051d19d2bc4b9
